version: 5.3.3.{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
test: off

os: Visual Studio 2019

nuget:
  disable_publish_on_pr: true

install:
  - npm install -g npm
  - npm --version
  - ps: Install-Product node LTS
  - node --version
  - dotnet --version

build_script:
  - cmd: yarn build-ci

artifacts:
- path: 'artifacts\*.nupkg'
  name: NuGet

deploy:
- provider: NuGet
  server: https://www.myget.org/F/graphql-dotnet/api/v2/package
  api_key:
    secure: +l1vfBMajn1WfmXkQ2LdILKxK4fQ5AHSnnU1kf11Bn1xRGUOTCdPhLwHx232piEn
  skip_symbols: false
  on:
    branch:
      - master
      - dev
